### ISSUE TITLE
Withdrawing from contract

### ISSUE THREAD

**Issue by charlie-eth** [sky-ecosystem/dockerized-auction-keeper#9]
I see I should be running this:

`./stop-keeper.sh flip-eth-a`

But I get:

`Error response from daemon: Container *************************** is not running
`

So please help figure out how to remove DAI from the contract!

**Comment by grandizzy** [comment]
@calbertuk this works with latest master, pls git pull and ./cleanup.sh then retry

**Comment by charlie-eth** [comment]
```
parity:/opt/keeper# git pull
Already up to date.
parity:/opt/keeper# ./stop-keeper.sh flip-eth-a
Error response from daemon: Container is not running
parity:/opt/keeper#

```

**Comment by grandizzy** [comment]
keeper should be running with ```./start-keeper.sh  flip-eth-a``` run ```./stop-keeper.sh flip-eth-a``` when keeper is up. let me know if that did it for you and will update README

**Comment by charlie-eth** [comment]
Issue is that keeper stops because #10 so there should be a way to exit without the assumption that the keeper is running.

**Comment by charlie-eth** [comment]
Make sure the keeper is running when attempting to withdraw your funds
